name: Continuous Integration 

on: [pull_requests, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 18.x
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run sass
          npm run test
